#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RUN_STAMP="$(date +%Y%m%d_%H%M%S)"

export OUTPUT_DIR="${OUTPUT_DIR:-../outputs/spatial_ot/cohort_multilevel_ot_deep_segmentation_${RUN_STAMP}}"
export COMPUTE_DEVICE="${COMPUTE_DEVICE:-cuda}"
export AUTO_N_CLUSTERS="${AUTO_N_CLUSTERS:-1}"
export CANDIDATE_N_CLUSTERS="${CANDIDATE_N_CLUSTERS:-15-25}"
export MIN_SUBREGIONS_PER_CLUSTER="${MIN_SUBREGIONS_PER_CLUSTER:-50}"
export MAX_SUBREGIONS="${MAX_SUBREGIONS:-8000}"
export BASIC_NICHE_SIZE_UM="${BASIC_NICHE_SIZE_UM:-40}"
export MIN_CELLS="${MIN_CELLS:-25}"

export SUBREGION_CONSTRUCTION_METHOD="${SUBREGION_CONSTRUCTION_METHOD:-deep_segmentation}"
export DEEP_SEGMENTATION_KNN="${DEEP_SEGMENTATION_KNN:-12}"
export DEEP_SEGMENTATION_FEATURE_DIMS="${DEEP_SEGMENTATION_FEATURE_DIMS:-32}"
export DEEP_SEGMENTATION_FEATURE_WEIGHT="${DEEP_SEGMENTATION_FEATURE_WEIGHT:-1.0}"
export DEEP_SEGMENTATION_SPATIAL_WEIGHT="${DEEP_SEGMENTATION_SPATIAL_WEIGHT:-0.05}"
export DEEP_SEGMENTATION_REFINEMENT_ITERS="${DEEP_SEGMENTATION_REFINEMENT_ITERS:-6}"

export DEEP_FEATURE_METHOD="${DEEP_FEATURE_METHOD:-autoencoder}"
export DEEP_OUTPUT_EMBEDDING="${DEEP_OUTPUT_EMBEDDING:-context}"
export DEEP_OUTPUT_OBSM_KEY="${DEEP_OUTPUT_OBSM_KEY:-X_spatial_ot_deep_context_autoencoder}"
export DEEP_DEVICE="${DEEP_DEVICE:-cuda}"
export DEEP_LATENT_DIM="${DEEP_LATENT_DIM:-32}"
export DEEP_HIDDEN_DIM="${DEEP_HIDDEN_DIM:-512}"
export DEEP_LAYERS="${DEEP_LAYERS:-2}"
export DEEP_NEIGHBOR_K="${DEEP_NEIGHBOR_K:-8}"
export DEEP_EPOCHS="${DEEP_EPOCHS:-8}"
export DEEP_BATCH_SIZE="${DEEP_BATCH_SIZE:-32768}"
export DEEP_VALIDATION="${DEEP_VALIDATION:-none}"
export DEEP_VALIDATION_CONTEXT_MODE="${DEEP_VALIDATION_CONTEXT_MODE:-inductive}"
export DEEP_SAVE_MODEL="${DEEP_SAVE_MODEL:-1}"

exec bash run_prepared_cohort_gpu.sh
