#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

VENV_DIR="${VENV_DIR:-../.venv}"
PYTHON_BIN="${PYTHON_BIN:-${VENV_DIR}/bin/python}"
INPUT_H5AD="${INPUT_H5AD:-../spatial_ot_input/spatial_ot_input_pooled.h5ad}"
OUTPUT_DIR="${OUTPUT_DIR:-../work/spatial_ot_runs/cohort_optimal_search}"
FEATURE_OBSM_KEY="${FEATURE_OBSM_KEY:-X_spatial_ot_x_svd_512}"
SPATIAL_X_KEY="${SPATIAL_X_KEY:-pooled_cell_x}"
SPATIAL_Y_KEY="${SPATIAL_Y_KEY:-pooled_cell_y}"
SAMPLE_OBS_KEY="${SAMPLE_OBS_KEY:-sample_id}"
SPATIAL_SCALE="${SPATIAL_SCALE:-0.2737012522439323}"
COMPUTE_DEVICE="${COMPUTE_DEVICE:-cuda}"
TIME_BUDGET_HOURS="${TIME_BUDGET_HOURS:-20}"
N_CLUSTERS="${N_CLUSTERS:-8}"
ATOMS_PER_CLUSTER="${ATOMS_PER_CLUSTER:-8}"
RADIUS_UM="${RADIUS_UM:-80}"
STRIDE_UM="${STRIDE_UM:-80}"
BASIC_NICHE_SIZE_UM="${BASIC_NICHE_SIZE_UM:-50}"
MIN_CELLS="${MIN_CELLS:-25}"
MAX_SUBREGIONS="${MAX_SUBREGIONS:-1500}"
MIN_SUBREGIONS_PER_CLUSTER="${MIN_SUBREGIONS_PER_CLUSTER:-50}"
LAMBDA_X="${LAMBDA_X:-0.35}"
LAMBDA_Y="${LAMBDA_Y:-1.0}"
GEOMETRY_EPS="${GEOMETRY_EPS:-0.03}"
OT_EPS="${OT_EPS:-0.03}"
RHO="${RHO:-0.5}"
GEOMETRY_SAMPLES="${GEOMETRY_SAMPLES:-192}"
COMPRESSED_SUPPORT_SIZE="${COMPRESSED_SUPPORT_SIZE:-96}"
ALIGN_ITERS="${ALIGN_ITERS:-4}"
N_INIT="${N_INIT:-5}"
OVERLAP_CONSISTENCY_WEIGHT="${OVERLAP_CONSISTENCY_WEIGHT:-0.05}"
OVERLAP_JACCARD_MIN="${OVERLAP_JACCARD_MIN:-0.15}"
OVERLAP_CONTRAST_SCALE="${OVERLAP_CONTRAST_SCALE:-1.0}"
SUBREGION_CONSTRUCTION_METHOD="${SUBREGION_CONSTRUCTION_METHOD:-data_driven}"
SUBREGION_CLUSTERING_METHOD="${SUBREGION_CLUSTERING_METHOD:-heterogeneity_descriptor_niche}"
SUBREGION_LATENT_EMBEDDING_MODE="${SUBREGION_LATENT_EMBEDDING_MODE:-mean_std_shrunk}"
SUBREGION_LATENT_SHRINKAGE_TAU="${SUBREGION_LATENT_SHRINKAGE_TAU:-25}"
SUBREGION_LATENT_HETEROGENEITY_WEIGHT="${SUBREGION_LATENT_HETEROGENEITY_WEIGHT:-0.5}"
SUBREGION_LATENT_SAMPLE_PRIOR_WEIGHT="${SUBREGION_LATENT_SAMPLE_PRIOR_WEIGHT:-0.5}"
SUBREGION_LATENT_CODEBOOK_SIZE="${SUBREGION_LATENT_CODEBOOK_SIZE:-32}"
SUBREGION_LATENT_CODEBOOK_SAMPLE_SIZE="${SUBREGION_LATENT_CODEBOOK_SAMPLE_SIZE:-50000}"
HETEROGENEITY_COMPOSITION_WEIGHT="${HETEROGENEITY_COMPOSITION_WEIGHT:-0.20}"
HETEROGENEITY_DIVERSITY_WEIGHT="${HETEROGENEITY_DIVERSITY_WEIGHT:-0.15}"
HETEROGENEITY_SPATIAL_FIELD_WEIGHT="${HETEROGENEITY_SPATIAL_FIELD_WEIGHT:-0.35}"
HETEROGENEITY_PAIR_COOCCURRENCE_WEIGHT="${HETEROGENEITY_PAIR_COOCCURRENCE_WEIGHT:-0.30}"
HETEROGENEITY_PAIR_DISTANCE_BINS="${HETEROGENEITY_PAIR_DISTANCE_BINS:-0.25,0.5,1.0,2.0}"
HETEROGENEITY_PAIR_GRAPH_MODE="${HETEROGENEITY_PAIR_GRAPH_MODE:-all_pairs}"
HETEROGENEITY_PAIR_GRAPH_K="${HETEROGENEITY_PAIR_GRAPH_K:-8}"
HETEROGENEITY_PAIR_GRAPH_RADIUS="${HETEROGENEITY_PAIR_GRAPH_RADIUS:-}"
HETEROGENEITY_PAIR_BIN_NORMALIZATION="${HETEROGENEITY_PAIR_BIN_NORMALIZATION:-per_bin}"
HETEROGENEITY_TRANSPORT_MAX_SUBREGIONS="${HETEROGENEITY_TRANSPORT_MAX_SUBREGIONS:-800}"
HETEROGENEITY_TRANSPORT_FEATURE_MODE="${HETEROGENEITY_TRANSPORT_FEATURE_MODE:-soft_codebook}"
HETEROGENEITY_TRANSPORT_FEATURE_COST="${HETEROGENEITY_TRANSPORT_FEATURE_COST:-hellinger_codebook}"
HETEROGENEITY_TRANSPORT_MARKER_FEATURE_WEIGHT="${HETEROGENEITY_TRANSPORT_MARKER_FEATURE_WEIGHT:-0.5}"
HETEROGENEITY_TRANSPORT_CODEBOOK_FEATURE_WEIGHT="${HETEROGENEITY_TRANSPORT_CODEBOOK_FEATURE_WEIGHT:-0.5}"
HETEROGENEITY_FUSED_OT_FEATURE_WEIGHT="${HETEROGENEITY_FUSED_OT_FEATURE_WEIGHT:-0.5}"
HETEROGENEITY_FUSED_OT_COORDINATE_WEIGHT="${HETEROGENEITY_FUSED_OT_COORDINATE_WEIGHT:-0.5}"
HETEROGENEITY_FUSED_OT_SOLVER="${HETEROGENEITY_FUSED_OT_SOLVER:-emd}"
HETEROGENEITY_FUSED_OT_EPSILON="${HETEROGENEITY_FUSED_OT_EPSILON:-0.05}"
HETEROGENEITY_FGW_ALPHA="${HETEROGENEITY_FGW_ALPHA:-0.5}"
HETEROGENEITY_FGW_SOLVER="${HETEROGENEITY_FGW_SOLVER:-conditional_gradient}"
HETEROGENEITY_FGW_EPSILON="${HETEROGENEITY_FGW_EPSILON:-0.05}"
HETEROGENEITY_FGW_LOSS_FUN="${HETEROGENEITY_FGW_LOSS_FUN:-square_loss}"
HETEROGENEITY_FGW_MAX_ITER="${HETEROGENEITY_FGW_MAX_ITER:-500}"
HETEROGENEITY_FGW_TOL="${HETEROGENEITY_FGW_TOL:-1e-7}"
HETEROGENEITY_FGW_N_INIT="${HETEROGENEITY_FGW_N_INIT:-3}"
HETEROGENEITY_FGW_INIT="${HETEROGENEITY_FGW_INIT:-outer_product,feature_ot,coordinate_ot}"
HETEROGENEITY_FGW_STRUCTURE_SCALE="${HETEROGENEITY_FGW_STRUCTURE_SCALE:-global_median}"
HETEROGENEITY_FGW_STRUCTURE_CLIP="${HETEROGENEITY_FGW_STRUCTURE_CLIP:-3.0}"
HETEROGENEITY_FGW_PARTIAL="${HETEROGENEITY_FGW_PARTIAL:-0}"
HETEROGENEITY_FGW_PARTIAL_MASS="${HETEROGENEITY_FGW_PARTIAL_MASS:-0.85}"
HETEROGENEITY_FGW_PARTIAL_REG="${HETEROGENEITY_FGW_PARTIAL_REG:-0.05}"
SUBREGION_FEATURE_WEIGHT="${SUBREGION_FEATURE_WEIGHT:-0}"
SUBREGION_FEATURE_DIMS="${SUBREGION_FEATURE_DIMS:-16}"
DEEP_SEGMENTATION_KNN="${DEEP_SEGMENTATION_KNN:-12}"
DEEP_SEGMENTATION_FEATURE_DIMS="${DEEP_SEGMENTATION_FEATURE_DIMS:-32}"
DEEP_SEGMENTATION_FEATURE_WEIGHT="${DEEP_SEGMENTATION_FEATURE_WEIGHT:-1.0}"
DEEP_SEGMENTATION_SPATIAL_WEIGHT="${DEEP_SEGMENTATION_SPATIAL_WEIGHT:-0.05}"
JOINT_REFINEMENT_ITERS="${JOINT_REFINEMENT_ITERS:-2}"
JOINT_REFINEMENT_KNN="${JOINT_REFINEMENT_KNN:-12}"
JOINT_REFINEMENT_FEATURE_DIMS="${JOINT_REFINEMENT_FEATURE_DIMS:-32}"
JOINT_REFINEMENT_CLUSTER_WEIGHT="${JOINT_REFINEMENT_CLUSTER_WEIGHT:-1.0}"
JOINT_REFINEMENT_SPATIAL_WEIGHT="${JOINT_REFINEMENT_SPATIAL_WEIGHT:-0.25}"
JOINT_REFINEMENT_CUT_WEIGHT="${JOINT_REFINEMENT_CUT_WEIGHT:-0.5}"
JOINT_REFINEMENT_MAX_MOVE_FRACTION="${JOINT_REFINEMENT_MAX_MOVE_FRACTION:-0.05}"
JOINT_REFINEMENT_ACCEPTANCE_MARGIN="${JOINT_REFINEMENT_ACCEPTANCE_MARGIN:-1e-3}"
ALLOW_OBSERVED_HULL_GEOMETRY="${ALLOW_OBSERVED_HULL_GEOMETRY:-0}"
REGION_OBS_KEY="${REGION_OBS_KEY:-}"
REGION_GEOMETRY_JSON="${REGION_GEOMETRY_JSON:-}"
SHAPE_DIAGNOSTICS="${SHAPE_DIAGNOSTICS:-1}"
SHAPE_LEAKAGE_PERMUTATIONS="${SHAPE_LEAKAGE_PERMUTATIONS:-64}"
KEEP_TOP_K="${KEEP_TOP_K:-3}"
DEEP_FEATURE_METHOD="${DEEP_FEATURE_METHOD:-autoencoder}"
DEEP_OUTPUT_EMBEDDING="${DEEP_OUTPUT_EMBEDDING:-context}"
DEEP_OUTPUT_OBSM_KEY="${DEEP_OUTPUT_OBSM_KEY:-X_spatial_ot_deep_context_autoencoder}"
DEEP_DEVICE="${DEEP_DEVICE:-cuda}"
DEEP_LATENT_DIM="${DEEP_LATENT_DIM:-64}"
DEEP_HIDDEN_DIM="${DEEP_HIDDEN_DIM:-1024}"
DEEP_LAYERS="${DEEP_LAYERS:-3}"
DEEP_NEIGHBOR_K="${DEEP_NEIGHBOR_K:-8}"
DEEP_GRAPH_LAYERS="${DEEP_GRAPH_LAYERS:-2}"
DEEP_GRAPH_MAX_NEIGHBORS="${DEEP_GRAPH_MAX_NEIGHBORS:-64}"
DEEP_FULL_BATCH_MAX_CELLS="${DEEP_FULL_BATCH_MAX_CELLS:-50000}"
DEEP_EPOCHS="${DEEP_EPOCHS:-30}"
DEEP_BATCH_SIZE="${DEEP_BATCH_SIZE:-32768}"
DEEP_LR="${DEEP_LR:-0.001}"
DEEP_WEIGHT_DECAY="${DEEP_WEIGHT_DECAY:-0.0001}"
DEEP_VALIDATION="${DEEP_VALIDATION:-spatial_block}"
DEEP_VALIDATION_CONTEXT_MODE="${DEEP_VALIDATION_CONTEXT_MODE:-inductive}"
DEEP_RECONSTRUCTION_WEIGHT="${DEEP_RECONSTRUCTION_WEIGHT:-1.0}"
DEEP_CONTEXT_WEIGHT="${DEEP_CONTEXT_WEIGHT:-0.5}"
DEEP_CONTRASTIVE_WEIGHT="${DEEP_CONTRASTIVE_WEIGHT:-0.1}"
DEEP_VARIANCE_WEIGHT="${DEEP_VARIANCE_WEIGHT:-0.1}"
DEEP_DECORRELATION_WEIGHT="${DEEP_DECORRELATION_WEIGHT:-0.01}"
DEEP_ALLOW_JOINT_OT_EMBEDDING="${DEEP_ALLOW_JOINT_OT_EMBEDDING:-0}"
DEEP_SAVE_MODEL="${DEEP_SAVE_MODEL:-1}"

if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Virtual environment python not found: $PYTHON_BIN" >&2
  echo "Run 'bash scripts/install_env.sh' from the spatial_ot directory first." >&2
  exit 1
fi

EXTRA_FLAGS=()
if [[ "$ALLOW_OBSERVED_HULL_GEOMETRY" == "1" ]]; then
  EXTRA_FLAGS+=(--allow-observed-hull-geometry)
else
  EXTRA_FLAGS+=(--no-allow-observed-hull-geometry)
fi
if [[ "$SHAPE_DIAGNOSTICS" == "1" ]]; then
  EXTRA_FLAGS+=(--shape-diagnostics)
else
  EXTRA_FLAGS+=(--no-shape-diagnostics)
fi
EXTRA_FLAGS+=(--shape-leakage-permutations "$SHAPE_LEAKAGE_PERMUTATIONS")
if [[ -n "$REGION_OBS_KEY" ]]; then
  EXTRA_FLAGS+=(--region-obs-key "$REGION_OBS_KEY")
fi
if [[ -n "$REGION_GEOMETRY_JSON" ]]; then
  EXTRA_FLAGS+=(--region-geometry-json "$REGION_GEOMETRY_JSON")
fi
if [[ -n "$HETEROGENEITY_PAIR_GRAPH_RADIUS" ]]; then
  EXTRA_FLAGS+=(--heterogeneity-pair-graph-radius "$HETEROGENEITY_PAIR_GRAPH_RADIUS")
fi
if [[ "$HETEROGENEITY_FGW_PARTIAL" == "1" ]]; then
  EXTRA_FLAGS+=(--heterogeneity-fgw-partial)
else
  EXTRA_FLAGS+=(--no-heterogeneity-fgw-partial)
fi

DEEP_FLAGS=()
if [[ "$DEEP_FEATURE_METHOD" != "none" ]]; then
  DEEP_FLAGS+=(
    --deep-feature-method "$DEEP_FEATURE_METHOD"
    --deep-output-embedding "$DEEP_OUTPUT_EMBEDDING"
    --deep-output-obsm-key "$DEEP_OUTPUT_OBSM_KEY"
    --deep-device "$DEEP_DEVICE"
    --deep-latent-dim "$DEEP_LATENT_DIM"
    --deep-hidden-dim "$DEEP_HIDDEN_DIM"
    --deep-layers "$DEEP_LAYERS"
    --deep-neighbor-k "$DEEP_NEIGHBOR_K"
    --deep-graph-layers "$DEEP_GRAPH_LAYERS"
    --deep-graph-max-neighbors "$DEEP_GRAPH_MAX_NEIGHBORS"
    --deep-full-batch-max-cells "$DEEP_FULL_BATCH_MAX_CELLS"
    --deep-epochs "$DEEP_EPOCHS"
    --deep-batch-size "$DEEP_BATCH_SIZE"
    --deep-lr "$DEEP_LR"
    --deep-weight-decay "$DEEP_WEIGHT_DECAY"
    --deep-validation "$DEEP_VALIDATION"
    --deep-validation-context-mode "$DEEP_VALIDATION_CONTEXT_MODE"
    --deep-reconstruction-weight "$DEEP_RECONSTRUCTION_WEIGHT"
    --deep-context-weight "$DEEP_CONTEXT_WEIGHT"
    --deep-contrastive-weight "$DEEP_CONTRASTIVE_WEIGHT"
    --deep-variance-weight "$DEEP_VARIANCE_WEIGHT"
    --deep-decorrelation-weight "$DEEP_DECORRELATION_WEIGHT"
  )
  if [[ "$DEEP_ALLOW_JOINT_OT_EMBEDDING" == "1" ]]; then
    DEEP_FLAGS+=(--deep-allow-joint-ot-embedding)
  else
    DEEP_FLAGS+=(--no-deep-allow-joint-ot-embedding)
  fi
  if [[ "$DEEP_SAVE_MODEL" == "1" ]]; then
    DEEP_FLAGS+=(--deep-save-model)
  else
    DEEP_FLAGS+=(--no-deep-save-model)
  fi
fi

"$PYTHON_BIN" -m spatial_ot optimal-search \
  --input-h5ad "$INPUT_H5AD" \
  --output-dir "$OUTPUT_DIR" \
  --feature-obsm-key "$FEATURE_OBSM_KEY" \
  --spatial-x-key "$SPATIAL_X_KEY" \
  --spatial-y-key "$SPATIAL_Y_KEY" \
  --sample-obs-key "$SAMPLE_OBS_KEY" \
  --spatial-scale "$SPATIAL_SCALE" \
  --compute-device "$COMPUTE_DEVICE" \
  --time-budget-hours "$TIME_BUDGET_HOURS" \
  --keep-top-k "$KEEP_TOP_K" \
  --n-clusters "$N_CLUSTERS" \
  --atoms-per-cluster "$ATOMS_PER_CLUSTER" \
  --radius-um "$RADIUS_UM" \
  --stride-um "$STRIDE_UM" \
  --basic-niche-size-um "$BASIC_NICHE_SIZE_UM" \
  --min-cells "$MIN_CELLS" \
  --max-subregions "$MAX_SUBREGIONS" \
  --min-subregions-per-cluster "$MIN_SUBREGIONS_PER_CLUSTER" \
  --lambda-x "$LAMBDA_X" \
  --lambda-y "$LAMBDA_Y" \
  --geometry-eps "$GEOMETRY_EPS" \
  --ot-eps "$OT_EPS" \
  --rho "$RHO" \
  --geometry-samples "$GEOMETRY_SAMPLES" \
  --compressed-support-size "$COMPRESSED_SUPPORT_SIZE" \
  --align-iters "$ALIGN_ITERS" \
  --n-init "$N_INIT" \
  --overlap-consistency-weight "$OVERLAP_CONSISTENCY_WEIGHT" \
  --overlap-jaccard-min "$OVERLAP_JACCARD_MIN" \
  --overlap-contrast-scale "$OVERLAP_CONTRAST_SCALE" \
  --subregion-construction-method "$SUBREGION_CONSTRUCTION_METHOD" \
  --subregion-clustering-method "$SUBREGION_CLUSTERING_METHOD" \
  --subregion-latent-embedding-mode "$SUBREGION_LATENT_EMBEDDING_MODE" \
  --subregion-latent-shrinkage-tau "$SUBREGION_LATENT_SHRINKAGE_TAU" \
  --subregion-latent-heterogeneity-weight "$SUBREGION_LATENT_HETEROGENEITY_WEIGHT" \
  --subregion-latent-sample-prior-weight "$SUBREGION_LATENT_SAMPLE_PRIOR_WEIGHT" \
  --subregion-latent-codebook-size "$SUBREGION_LATENT_CODEBOOK_SIZE" \
  --subregion-latent-codebook-sample-size "$SUBREGION_LATENT_CODEBOOK_SAMPLE_SIZE" \
  --heterogeneity-composition-weight "$HETEROGENEITY_COMPOSITION_WEIGHT" \
  --heterogeneity-diversity-weight "$HETEROGENEITY_DIVERSITY_WEIGHT" \
  --heterogeneity-spatial-field-weight "$HETEROGENEITY_SPATIAL_FIELD_WEIGHT" \
  --heterogeneity-pair-cooccurrence-weight "$HETEROGENEITY_PAIR_COOCCURRENCE_WEIGHT" \
  --heterogeneity-pair-distance-bins "$HETEROGENEITY_PAIR_DISTANCE_BINS" \
  --heterogeneity-pair-graph-mode "$HETEROGENEITY_PAIR_GRAPH_MODE" \
  --heterogeneity-pair-graph-k "$HETEROGENEITY_PAIR_GRAPH_K" \
  --heterogeneity-pair-bin-normalization "$HETEROGENEITY_PAIR_BIN_NORMALIZATION" \
  --heterogeneity-transport-max-subregions "$HETEROGENEITY_TRANSPORT_MAX_SUBREGIONS" \
  --heterogeneity-transport-feature-mode "$HETEROGENEITY_TRANSPORT_FEATURE_MODE" \
  --heterogeneity-transport-feature-cost "$HETEROGENEITY_TRANSPORT_FEATURE_COST" \
  --heterogeneity-transport-marker-feature-weight "$HETEROGENEITY_TRANSPORT_MARKER_FEATURE_WEIGHT" \
  --heterogeneity-transport-codebook-feature-weight "$HETEROGENEITY_TRANSPORT_CODEBOOK_FEATURE_WEIGHT" \
  --heterogeneity-fused-ot-feature-weight "$HETEROGENEITY_FUSED_OT_FEATURE_WEIGHT" \
  --heterogeneity-fused-ot-coordinate-weight "$HETEROGENEITY_FUSED_OT_COORDINATE_WEIGHT" \
  --heterogeneity-fused-ot-solver "$HETEROGENEITY_FUSED_OT_SOLVER" \
  --heterogeneity-fused-ot-epsilon "$HETEROGENEITY_FUSED_OT_EPSILON" \
  --heterogeneity-fgw-alpha "$HETEROGENEITY_FGW_ALPHA" \
  --heterogeneity-fgw-solver "$HETEROGENEITY_FGW_SOLVER" \
  --heterogeneity-fgw-epsilon "$HETEROGENEITY_FGW_EPSILON" \
  --heterogeneity-fgw-loss-fun "$HETEROGENEITY_FGW_LOSS_FUN" \
  --heterogeneity-fgw-max-iter "$HETEROGENEITY_FGW_MAX_ITER" \
  --heterogeneity-fgw-tol "$HETEROGENEITY_FGW_TOL" \
  --heterogeneity-fgw-n-init "$HETEROGENEITY_FGW_N_INIT" \
  --heterogeneity-fgw-init "$HETEROGENEITY_FGW_INIT" \
  --heterogeneity-fgw-structure-scale "$HETEROGENEITY_FGW_STRUCTURE_SCALE" \
  --heterogeneity-fgw-structure-clip "$HETEROGENEITY_FGW_STRUCTURE_CLIP" \
  --heterogeneity-fgw-partial-mass "$HETEROGENEITY_FGW_PARTIAL_MASS" \
  --heterogeneity-fgw-partial-reg "$HETEROGENEITY_FGW_PARTIAL_REG" \
  --subregion-feature-weight "$SUBREGION_FEATURE_WEIGHT" \
  --subregion-feature-dims "$SUBREGION_FEATURE_DIMS" \
  --deep-segmentation-knn "$DEEP_SEGMENTATION_KNN" \
  --deep-segmentation-feature-dims "$DEEP_SEGMENTATION_FEATURE_DIMS" \
  --deep-segmentation-feature-weight "$DEEP_SEGMENTATION_FEATURE_WEIGHT" \
  --deep-segmentation-spatial-weight "$DEEP_SEGMENTATION_SPATIAL_WEIGHT" \
  --joint-refinement-iters "$JOINT_REFINEMENT_ITERS" \
  --joint-refinement-knn "$JOINT_REFINEMENT_KNN" \
  --joint-refinement-feature-dims "$JOINT_REFINEMENT_FEATURE_DIMS" \
  --joint-refinement-cluster-weight "$JOINT_REFINEMENT_CLUSTER_WEIGHT" \
  --joint-refinement-spatial-weight "$JOINT_REFINEMENT_SPATIAL_WEIGHT" \
  --joint-refinement-cut-weight "$JOINT_REFINEMENT_CUT_WEIGHT" \
  --joint-refinement-max-move-fraction "$JOINT_REFINEMENT_MAX_MOVE_FRACTION" \
  --joint-refinement-acceptance-margin "$JOINT_REFINEMENT_ACCEPTANCE_MARGIN" \
  "${EXTRA_FLAGS[@]}" \
  "${DEEP_FLAGS[@]}"
