#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

RUN_STAMP="$(date +%Y%m%d_%H%M%S)"

export OUTPUT_DIR="${OUTPUT_DIR:-../outputs/spatial_ot/visium_hd_cohort_multilevel_ot_joint_refinement_vram70_${RUN_STAMP}}"
export COMPUTE_DEVICE="${COMPUTE_DEVICE:-cuda}"
export AUTO_N_CLUSTERS="${AUTO_N_CLUSTERS:-1}"
export CANDIDATE_N_CLUSTERS="${CANDIDATE_N_CLUSTERS:-15-25}"
export MIN_SUBREGIONS_PER_CLUSTER="${MIN_SUBREGIONS_PER_CLUSTER:-50}"
export MAX_SUBREGIONS="${MAX_SUBREGIONS:-8000}"
export BASIC_NICHE_SIZE_UM="${BASIC_NICHE_SIZE_UM:-40}"
export MIN_CELLS="${MIN_CELLS:-25}"

export SUBREGION_CONSTRUCTION_METHOD="${SUBREGION_CONSTRUCTION_METHOD:-joint_refinement}"
export SUBREGION_CLUSTERING_METHOD="${SUBREGION_CLUSTERING_METHOD:-heterogeneity_descriptor_niche}"
export DEEP_SEGMENTATION_KNN="${DEEP_SEGMENTATION_KNN:-12}"
export DEEP_SEGMENTATION_FEATURE_DIMS="${DEEP_SEGMENTATION_FEATURE_DIMS:-32}"
export DEEP_SEGMENTATION_FEATURE_WEIGHT="${DEEP_SEGMENTATION_FEATURE_WEIGHT:-1.0}"
export DEEP_SEGMENTATION_SPATIAL_WEIGHT="${DEEP_SEGMENTATION_SPATIAL_WEIGHT:-0.05}"
export DEEP_SEGMENTATION_REFINEMENT_ITERS="${DEEP_SEGMENTATION_REFINEMENT_ITERS:-6}"
export JOINT_REFINEMENT_ITERS="${JOINT_REFINEMENT_ITERS:-2}"
export JOINT_REFINEMENT_KNN="${JOINT_REFINEMENT_KNN:-12}"
export JOINT_REFINEMENT_FEATURE_DIMS="${JOINT_REFINEMENT_FEATURE_DIMS:-32}"
export JOINT_REFINEMENT_CLUSTER_WEIGHT="${JOINT_REFINEMENT_CLUSTER_WEIGHT:-1.0}"
export JOINT_REFINEMENT_SPATIAL_WEIGHT="${JOINT_REFINEMENT_SPATIAL_WEIGHT:-0.25}"
export JOINT_REFINEMENT_CUT_WEIGHT="${JOINT_REFINEMENT_CUT_WEIGHT:-0.5}"
export JOINT_REFINEMENT_MAX_MOVE_FRACTION="${JOINT_REFINEMENT_MAX_MOVE_FRACTION:-0.05}"
export JOINT_REFINEMENT_ACCEPTANCE_MARGIN="${JOINT_REFINEMENT_ACCEPTANCE_MARGIN:-1e-3}"

export DEEP_FEATURE_METHOD="${DEEP_FEATURE_METHOD:-autoencoder}"
export DEEP_OUTPUT_EMBEDDING="${DEEP_OUTPUT_EMBEDDING:-context}"
export DEEP_OUTPUT_OBSM_KEY="${DEEP_OUTPUT_OBSM_KEY:-X_spatial_ot_deep_context_autoencoder}"
export DEEP_NEIGHBOR_K="${DEEP_NEIGHBOR_K:-8}"
export DEEP_VALIDATION_CONTEXT_MODE="${DEEP_VALIDATION_CONTEXT_MODE:-inductive}"

# shellcheck source=scripts/_high_vram_deep_profile.sh
source "$SCRIPT_DIR/_high_vram_deep_profile.sh"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  env | sort | grep -E '^(INPUT_H5AD|OUTPUT_DIR|FEATURE_OBSM_KEY|SUBREGION_CONSTRUCTION_METHOD|DEEP_[A-Z0-9_]*|CUDA_[A-Z0-9_]*|SPATIAL_OT_CUDA_[A-Z0-9_]*|CPU_THREADS|TORCH_[A-Z0-9_]*|PYTORCH_[A-Z0-9_]*|OMP_NUM_THREADS|MKL_NUM_THREADS|OPENBLAS_NUM_THREADS)='
  exit 0
fi

exec bash "$SCRIPT_DIR/run_prepared_cohort_gpu.sh"
