#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

RUN_STAMP="$(date +%Y%m%d_%H%M%S)"

export INPUT_DIR="${XENIUM_INPUT_DIR:-../data_review/results}"
export INPUT_H5AD="${XENIUM_OUTPUT_H5AD:-../spatial_ot_input/xenium_spatial_ot_input_pooled.h5ad}"
export POOLED_INPUT_NAME="${POOLED_INPUT_NAME:-xenium_spatial_ot_input_pooled.h5ad}"
export OUTPUT_DIR="${OUTPUT_DIR:-../outputs/spatial_ot/xenium_cohort_multilevel_ot_deep_expression_${RUN_STAMP}}"
export SAMPLE_GLOB="${SAMPLE_GLOB:-xenium_*_processed.h5ad}"
export SAMPLE_ID_PREFIX="${SAMPLE_ID_PREFIX:-xenium_}"
export SAMPLE_ID_SUFFIX="${SAMPLE_ID_SUFFIX:-_processed}"
export SAMPLE_ID_CASE="${SAMPLE_ID_CASE:-lower}"
export ORIGINAL_SPATIAL_X_KEY="${ORIGINAL_SPATIAL_X_KEY:-x_centroid}"
export ORIGINAL_SPATIAL_Y_KEY="${ORIGINAL_SPATIAL_Y_KEY:-y_centroid}"
export SPATIAL_SCALE="${SPATIAL_SCALE:-1.0}"
export X_FEATURE_COMPONENTS="${X_FEATURE_COMPONENTS:-421}"
export PREPARED_FEATURE_OBSM_KEY="${PREPARED_FEATURE_OBSM_KEY:-X_spatial_ot_x_svd_${X_FEATURE_COMPONENTS}}"
export FEATURE_OBSM_KEY="${FEATURE_OBSM_KEY:-X}"
export POOL_ALL_INPUTS="${POOL_ALL_INPUTS:-1}"
export PREPARE_INPUTS_AHEAD="${PREPARE_INPUTS_AHEAD:-0}"
export COMPUTE_DEVICE="${COMPUTE_DEVICE:-cuda}"
export AUTO_N_CLUSTERS="${AUTO_N_CLUSTERS:-1}"
export CANDIDATE_N_CLUSTERS="${CANDIDATE_N_CLUSTERS:-8-16}"
export MIN_SUBREGIONS_PER_CLUSTER="${MIN_SUBREGIONS_PER_CLUSTER:-50}"
export MAX_SUBREGIONS="${MAX_SUBREGIONS:-8000}"
export BASIC_NICHE_SIZE_UM="${BASIC_NICHE_SIZE_UM:-50}"
export MIN_CELLS="${MIN_CELLS:-25}"
export RADIUS_UM="${RADIUS_UM:-100}"
export STRIDE_UM="${STRIDE_UM:-100}"
export DEFAULT_PLOT_SAMPLE_ID="${DEFAULT_PLOT_SAMPLE_ID:-xenium_cohort}"

export DEEP_FEATURE_METHOD="${DEEP_FEATURE_METHOD:-autoencoder}"
export DEEP_OUTPUT_EMBEDDING="${DEEP_OUTPUT_EMBEDDING:-intrinsic}"
export DEEP_OUTPUT_OBSM_KEY="${DEEP_OUTPUT_OBSM_KEY:-X_spatial_ot_deep_expression_autoencoder}"
export DEEP_DEVICE="${DEEP_DEVICE:-cuda}"
export DEEP_LATENT_DIM="${DEEP_LATENT_DIM:-64}"
export DEEP_HIDDEN_DIM="${DEEP_HIDDEN_DIM:-1024}"
export DEEP_LAYERS="${DEEP_LAYERS:-3}"
export DEEP_EPOCHS="${DEEP_EPOCHS:-8}"
export DEEP_BATCH_SIZE="${DEEP_BATCH_SIZE:-81920}"
export DEEP_VALIDATION="${DEEP_VALIDATION:-none}"
export DEEP_CONTEXT_WEIGHT="${DEEP_CONTEXT_WEIGHT:-0.0}"
export DEEP_CONTRASTIVE_WEIGHT="${DEEP_CONTRASTIVE_WEIGHT:-0.0}"

exec bash "$SCRIPT_DIR/run.sh"
